#!/usr/bin/env python3
"""
Generate data/matching.json from js/data.js — the shared matching dictionary
that both the browser and the cloud pipeline consume.

The cloud vote loader used to re-derive this by string-splitting js/data.js at
runtime (`src.split('const UNIVERSE_KEYWORDS = {')`), and separately kept
hand-copied duplicates of CAST_CODES and the stop-word list. Renaming a
constant or reformatting the file silently produced different keyword sets in
the browser and the cloud, with nothing to catch it.

js/data.js stays the human-editable source (it has to: the app loads plain
<script> tags with no build step). This script extracts the matching data into
JSON, and `--check` fails when the committed JSON is stale — wire that into CI
or run it before committing changes to js/data.js.

Usage:
    python scripts/build_matching_dict.py            # write data/matching.json
    python scripts/build_matching_dict.py --check    # exit 1 if out of date
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_JS = os.path.join(HERE, '..', 'js', 'data.js')
OUT = os.path.join(HERE, '..', 'data', 'matching.json')


def js_string_list(block):
    """Every single-quoted string in a JS array/set literal body."""
    return re.findall(r"'((?:[^'\\]|\\.)*)'", block)


def between(src, start, end, what):
    try:
        return src.split(start, 1)[1].split(end, 1)[0]
    except IndexError:
        raise SystemExit(f'Could not locate {what} in js/data.js — did the '
                         f'declaration change? Expected literal: {start!r}')


def extract():
    src = open(DATA_JS).read()

    kw_block = between(src, 'const UNIVERSE_KEYWORDS = {', '\n};', 'UNIVERSE_KEYWORDS')
    universe_keywords = {}
    for line in kw_block.splitlines():
        m = re.match(r"\s*'((?:[^'\\]|\\.)*)':\s*\[(.*)\],\s*$", line)
        if m:
            universe_keywords[m.group(1)] = js_string_list(m.group(2))

    universes = js_string_list(between(src, 'const POSEIDON_UNIVERSES = [', '\n];', 'POSEIDON_UNIVERSES'))
    anchors = js_string_list(between(src, 'const ANCHOR_WORDS = new Set([', '\n]);', 'ANCHOR_WORDS'))
    stop = between(src, "const STOP = new Set('", "'.split(' ')", 'STOP').split()

    cast_block = between(src, 'const CAST_CODES = {', '}', 'CAST_CODES')
    cast_codes = {m.group(1): m.group(2) for m in
                  re.finditer(r"(\d+)\s*:\s*'([^']+)'", cast_block)}

    if not (universe_keywords and universes and anchors and stop and cast_codes):
        raise SystemExit('Extraction produced an empty section — refusing to write.')

    return {
        '_generated_from': 'js/data.js',
        '_note': 'Generated by scripts/build_matching_dict.py. Edit js/data.js, not this file.',
        'universes': universes,
        'universe_keywords': universe_keywords,
        'anchor_words': sorted(anchors),
        'stop_words': sorted(set(stop)),
        'cast_codes': cast_codes,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    data = extract()
    fresh = json.dumps(data, indent=1, sort_keys=True)

    if args.check:
        try:
            current = open(OUT).read()
        except FileNotFoundError:
            raise SystemExit('data/matching.json is missing — run '
                             'scripts/build_matching_dict.py')
        if current.strip() != fresh.strip():
            raise SystemExit('data/matching.json is out of date with js/data.js — '
                             'run scripts/build_matching_dict.py and commit the result.')
        print('matching.json is in sync with js/data.js')
        return

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write(fresh + '\n')
    print(f'{len(data["universes"])} universes · '
          f'{len(data["universe_keywords"])} with curated keywords · '
          f'{len(data["anchor_words"])} anchor words · '
          f'{len(data["stop_words"])} stop words -> data/matching.json')


if __name__ == '__main__':
    main()
